# Первичный анализ и трансформация исходного датасета в версии Raw и Easy

## Исходный файл

### Анализ

In [29]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATASET_PATH = BASE_DIR / "data" / "data-15-structure-3.csv"

if DATASET_PATH.exists():
    df_orig = pd.read_csv(DATASET_PATH)
    print("Датасет успешно загружен.")
    print(f"Строк: {len(df_orig)}")
else:
    print(f"Файл не найден по пути: {DATASET_PATH}")

Датасет успешно загружен.
Строк: 23086

#### Общая информация

In [15]:
print(f"Размер датасета: {df_orig.shape}")

print("\nПервые 5 строк")
df_orig.head(5)

Размер датасета: (23086, 24)

Первые 5 строк

,Идентификатор записи реестра,Регистрационный номер,Дата регистрации,Название культурной ценности,Полноценное визуальное описание,Код,Классификация культурной ценности,Комментарий,Код [2],Категория культурной ценности,...,Комментарий [4],Высота,Ширина,Длина,Вес,Идентификатор записи реестра [2],Описание состояния сохранности,"Идентифицирующие признаки предмета (надписи, подписи, клейма, пометы, экслибрисы и т.п.)",дата создания объекта,дата обновления объекта
0,12669127,23565,2025-12-24,"Каменев И.Ю. ""Фазы луны"" (триптих, центральная...",NaN,16.0,ЖИВОПИСЬ,NaN,NaN,NaN,...,NaN,180 см,120 см,NaN,NaN,[],NaN,NaN,2025-12-24T15:53:29+03:00,2025-12-24T15:53:29+03:00
1,12669129,23566,2025-12-24,"Каменев И.Ю. ""Фазы луны"" (триптих, левая часть...",NaN,16.0,ЖИВОПИСЬ,NaN,NaN,NaN,...,NaN,180 см,60 см,NaN,NaN,[],NaN,NaN,2025-12-24T15:53:29+03:00,2025-12-24T15:53:29+03:00
2,12669131,23567,2025-12-24,"Каменев И.Ю. ""Фазы луны"" (триптих, правая част...",NaN,16.0,ЖИВОПИСЬ,NaN,NaN,NaN,...,NaN,180 см,60 см,NaN,NaN,[],NaN,NaN,2025-12-24T15:53:29+03:00,2025-12-24T15:53:29+03:00
3,12669133,23568,2025-12-24,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,16.0,ЖИВОПИСЬ,NaN,NaN,NaN,...,NaN,150 см,100 см,NaN,NaN,[],NaN,NaN,2025-12-24T15:53:29+03:00,2025-12-24T15:53:29+03:00
4,12669135,23569,2025-12-24,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,16.0,ЖИВОПИСЬ,NaN,NaN,NaN,...,NaN,80 см,60 см,NaN,NaN,[],NaN,NaN,2025-12-24T15:53:29+03:00,2025-12-24T15:53:29+03:00

In [16]:
print("Техническая информация:")
df_orig.info()

Техническая информация:
<class 'pandas.DataFrame'>
RangeIndex: 23086 entries, 0 to 23085
Data columns (total 24 columns):
 #   Column                                                                                    Non-Null Count  Dtype
---  ------                                                                                    --------------  -----
 0   Идентификатор записи реестра                                                              23086 non-null  int64
 1   Регистрационный номер                                                                     23086 non-null  int64
 2   Дата регистрации                                                                          23086 non-null  str
 3   Название культурной ценности                                                              21997 non-null  str
 4   Полноценное визуальное описание                                                           0 non-null      float64
 5   Код                                                                                       9742 non-null   float64
 6   Классификация культурной ценности                                                         9742 non-null   str
 7   Комментарий                                                                               0 non-null      float64
 8   Код [2]                                                                                   3234 non-null   float64
 9   Категория культурной ценности                                                             3234 non-null   str
 10  Комментарий [2]                                                                           0 non-null      float64
 11  Комментарий [3]                                                                           19 non-null     str
 12  Код [3]                                                                                   4467 non-null   float64
 13  Наименование                                                                              4467 non-null   str
 14  Комментарий [4]                                                                           0 non-null      float64
 15  Высота                                                                                    10816 non-null  str
 16  Ширина                                                                                    10814 non-null  str
 17  Длина                                                                                     2494 non-null   str
 18  Вес                                                                                       5 non-null      str
 19  Идентификатор записи реестра [2]                                                          23086 non-null  str
 20  Описание состояния сохранности                                                            4109 non-null   str
 21  Идентифицирующие признаки предмета (надписи, подписи, клейма, пометы, экслибрисы и т.п.)  20499 non-null  str
 22  дата создания объекта                                                                     23086 non-null  str
 23  дата обновления объекта                                                                   23086 non-null  str
dtypes: float64(7), int64(2), str(15)
memory usage: 4.2 MB

In [17]:
print("Распределение всех категорий в исходных данных:")
category_counts = df_orig['Классификация культурной ценности'].value_counts()
print(category_counts)

Распределение всех категорий в исходных данных:
Классификация культурной ценности
ИКОНА                                                 2718
ЖИВОПИСЬ                                              2592
РАЗНОЕ                                                1213
ПРЕДМЕТЫ НУМИЗМАТИКИ И БОНИСТИКИ                       682
ОБРАЗЦЫ ФЛОРЫ И ФАУНЫ                                  557
ОТТИСК                                                 477
АРХИВНЫЕ ДОКУМЕНТЫ                                     345
МОНЕТА / МЕДАЛЬ                                        239
РИСУНОК                                                179
ПРЕДМЕТЫ ФАЛЕРИСТИКИ И СФРАГИСТИКИ                     141
ПЕЧАТНЫЕ ИЗДАНИЯ                                        91
КЕРАМИКА                                                73
ОРУЖИЕ ХОЛОДНОЕ                                         68
ОРУЖИЕ ОГНЕСТРЕЛЬНОЕ                                    51
ВЫШИВКА                                                 48
ЭМАЛЬ                                                   48
РЕЛИГИОЗНЫЙ ПРЕДМЕТ                                     42
ЗОЛОТО, СЕРЕБРО / ЮВЕЛИРНОЕ ИЗДЕЛИЕ                     41
ЧАСЫ / ХРОНОМЕТР                                        34
СТЕКЛО                                                  33
ДОКУМЕНТ / КНИГА                                        25
ХУДОЖЕСТВЕННЫЕ ЦЕННОСТИ                                 19
СКУЛЬПТУРА / СТАТУЯ                                     15
МУЗЫКАЛЬНЫЕ ИНСТРУМЕНТЫ                                  3
МУЗЫКАЛЬНЫЙ ИНСТРУМЕНТ                                   2
МЕБЕЛЬ, ПРЕДМЕТ ОБСТАНОВКИ                               1
ИСТОРИЧЕСКИЕ ЦЕННОСТИ                                    1
КОВЕР / КОВРИК                                           1
КУЛЬТУРНЫЕ ЦЕННОСТИ, НАХОДЯЩИЕСЯ НА ПОСТОЯННОМ ХОА       1
МОЗАИКА                                                  1
ГОБЕЛЕН                                                  1
Name: count, dtype: int64

In [19]:
categories = ['ЖИВОПИСЬ', 'АРХИВНЫЕ ДОКУМЕНТЫ', 'МОНЕТА / МЕДАЛЬ']

print("--- ПРИМЕРЫ ДАННЫХ ИЗ РЕЕСТРА ---\n")

df_orig.columns = df_orig.columns.str.strip()

for cat in categories:
    print(f"=== КАТЕГОРИЯ: {cat} ===")
    
    # Берем 2 случайных примера, где название не пустое
    sample = df_orig[df_orig['Классификация культурной ценности'] == cat].dropna(subset=['Название культурной ценности']).sample(2)
    
    for i, row in sample.iterrows():
        print(f"ОБЪЕКТ: {row['Название культурной ценности']}")
        print(f"СОСТОЯНИЕ: {row['Описание состояния сохранности']}")
        print(f"ПРИЗНАКИ: {row['Идентифицирующие признаки предмета (надписи, подписи, клейма, пометы, экслибрисы и т.п.)']}")
        print(f"РАЗМЕРЫ: {row['Высота']} x {row['Ширина']}")
        print("-" * 30)
    print("\n")

--- ПРИМЕРЫ ДАННЫХ ИЗ РЕЕСТРА ---

=== КАТЕГОРИЯ: ЖИВОПИСЬ ===
ОБЪЕКТ: Мужской портрет    Автор: Неизвестный художник
СОСТОЯНИЕ: nan
ПРИЗНАКИ: Размеры: B. 59,5, Ш. 43    Инвентарный номер: Инв. №29. Старый инв. №297 по ИК ВКМ
РАЗМЕРЫ: nan x 43
------------------------------
ОБЪЕКТ: Брестская клятва (название придуманное)    Автор: Ахмаров Шамсудин Магомедович (художник)    Школа / Место издания: Россия, Северный Кавказ    Период оригинала: 4 четверть 20 век
СОСТОЯНИЕ: nan
ПРИЗНАКИ: Размеры: В. 200, Ш. 150 (приблизительно, без обрамления)    Ссылка на каталоги / инвентари: ЧГОМ: № 306
РАЗМЕРЫ: 200 x 150
------------------------------


=== КАТЕГОРИЯ: АРХИВНЫЕ ДОКУМЕНТЫ ===
ОБЪЕКТ: МОКМ КП-2405/8 Фотография. Сергеев В.К. Место съемки и дата неизвестны. Фотобумага, размер не зафиксирован. Поступление 1968 г.
СОСТОЯНИЕ: Не зафиксировано
ПРИЗНАКИ: Не зафиксировано
РАЗМЕРЫ: nan x nan
------------------------------
ОБЪЕКТ: ШКМ КП-877. Номер по ГК 14792298. Документ Название: "Удостоверение Поташина Аркадия Ивановича к медали "За взятие Берлина" А № 124 104 от 28 октября 1945 года". подлинник Датировка: 1945 Место создания: СССР Материал: бумага Техника: машинопись Размеры: 11х8см.
СОСТОЯНИЕ: Потертости, по краям загрязнения, углы закруглены
ПРИЗНАКИ: нет
РАЗМЕРЫ: nan x nan
------------------------------


=== КАТЕГОРИЯ: МОНЕТА / МЕДАЛЬ ===
ОБЪЕКТ: Георгиевский крест «За веру, царя, Отечество» Металл. Кон. 19 – нач. 20 в. ЯКМ КП 300
СОСТОЯНИЕ: Загрязнения
ПРИЗНАКИ: Надпись "ЯКИ 300"
РАЗМЕРЫ: nan x nan
------------------------------
ОБЪЕКТ: Монета. 2 копейки 1842 год Медь. Чеканка. Размер: диаметр 3,2 см. № по книге поступлений: КП-1074 № по инвентарной книге: Н-96 № по ГК: 6665052
СОСТОЯНИЕ: Медь потемнела, потертости
ПРИЗНАКИ: НЕТ
РАЗМЕРЫ: nan x nan
------------------------------

#### Проверка на пропуски

In [20]:
# Общая статистика

# Считаем общее количество строк
total_rows = len(df_orig)

# Считаем процент пропусков для КАЖДОЙ колонки отдельно
null_percentages = (df_orig[['Высота', 'Ширина', 'Длина', 'Вес']].isnull().sum() / total_rows) * 100

print("Процент пропусков по каждой колонке:")
print(null_percentages.map('{:.2f}%'.format))

# Средний процент "пустоты" именно по этим 4-м колонкам
total_nulls_in_subset = df_orig[['Высота', 'Ширина', 'Длина', 'Вес']].isnull().sum().sum()
total_cells_in_subset = total_rows * 4
actual_empty_percent = (total_nulls_in_subset / total_cells_in_subset) * 100

print(f"Средняя 'пустота' ключевых признаков: {actual_empty_percent:.2f}%")

Процент пропусков по каждой колонке:
Высота    53.15%
Ширина    53.16%
Длина     89.20%
Вес       99.98%
dtype: str
Средняя 'пустота' ключевых признаков: 73.87%

In [21]:
# Проверка описательных полей на наличие пропусков.

# Список столбцов с описательными характеристиками для анализа.
desc_columns = [
    'Название культурной ценности', 
    'Полноценное визуальное описание', 
    'Описание состояния сохранности', 
    'Идентифицирующие признаки предмета (надписи, подписи, клейма, пометы, экслибрисы и т.п.)'
]

# Формирование сводной таблицы с анализом пропущенных значений.
desc_stats = pd.DataFrame({
    'Заполнено (Non-Null)': df_orig[desc_columns].notnull().sum(),
    'Пусто (Null)': df_orig[desc_columns].isnull().sum(),
    'Процент пустоты': (df_orig[desc_columns].isnull().sum() / len(df_orig) * 100).map('{:.2f}%'.format)
})

print("Сравнение заполненности колонок с описаниями:")
display(desc_stats)

# Дополнительная проверка: а есть ли строки, где ВООБЩЕ НЕТ никакого описания?
# Проверяем строки, где все выбранные колонки пустые
total_empty_rows = df_orig[desc_columns].isnull().all(axis=1).sum()

print(f"\nОбъектов без единого слова описания (во всех {len(desc_columns)} колонках): {total_empty_rows}")
print(f"Это {total_empty_rows / len(df_orig) * 100:.2f}% от всей базы.")

Сравнение заполненности колонок с описаниями:

,Заполнено (Non-Null),Пусто (Null),Процент пустоты
Название культурной ценности,21997,1089,4.72%
Полноценное визуальное описание,0,23086,100.00%
Описание состояния сохранности,4109,18977,82.20%
"Идентифицирующие признаки предмета (надписи, подписи, клейма, пометы, экслибрисы и т.п.)",20499,2587,11.21%

Объектов без единого слова описания (во всех 4 колонках): 606
Это 2.62% от всей базы.

## Raw версия

### Анализ

#### Общая информация

In [97]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATASET_PATH = BASE_DIR / "data" / "culture_large_dataset_raw.csv"

if DATASET_PATH.exists():
    df_raw = pd.read_csv(DATASET_PATH)
    print("Датасет успешно загружен.")
    print(f"Строк: {len(df_raw)}")
else:
    print(f"Файл не найден по пути: {DATASET_PATH}")

Датасет успешно загружен.
Строк: 7550

In [71]:
print(f"Размер датасета: {df_raw.shape}")

print("\nПервые 5 строк")
df_raw.head(5)

Размер датасета: (7550, 14)

Первые 5 строк

,title,marks,condition,category,height,width,length,weight,create_date,target_group,is_painting_hint,is_icon_hint,is_coin_hint,is_doc_hint
0,"Каменев И.Ю. ""Фазы луны"" (триптих, центральная...",NaN,NaN,ЖИВОПИСЬ,180.0,120.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
1,"Каменев И.Ю. ""Фазы луны"" (триптих, левая часть...",NaN,NaN,ЖИВОПИСЬ,180.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
2,"Каменев И.Ю. ""Фазы луны"" (триптих, правая част...",NaN,NaN,ЖИВОПИСЬ,180.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
3,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,NaN,ЖИВОПИСЬ,150.0,100.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,1,0,0
4,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,NaN,ЖИВОПИСЬ,80.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,1,0,0

In [95]:
# Считаем общее количество строк
total_rows = len(df_raw)

# Считаем процент пропусков для КАЖДОЙ колонки отдельно
null_percentages = (df_raw[['height', 'width', 'length', 'weight']].isnull().sum() / total_rows) * 100

print("Процент пропусков по каждой колонке:")
print(null_percentages.map('{:.2f}%'.format))

# Средний процент "пустоты" именно по этим 4-м колонкам
total_nulls_in_subset = df_raw[['height', 'width', 'length', 'weight']].isnull().sum().sum()
total_cells_in_subset = total_rows * 4
actual_empty_percent = (total_nulls_in_subset / total_cells_in_subset) * 100

print(f"Средняя 'пустота' ключевых признаков: {actual_empty_percent:.2f}%")

Процент пропусков по каждой колонке:
height     36.68%
width      31.58%
length     97.44%
weight    100.00%
dtype: str
Средняя 'пустота' ключевых признаков: 66.42%

In [40]:
# Группируем данные по целевой группе и считаем сумму хинтов в каждой

hint_columns = ['is_painting_hint', 'is_icon_hint', 'is_coin_hint', 'is_doc_hint']

coverage_matrix = df_raw.groupby('target_group')[hint_columns].sum()

print("Матрица покрытия (хинты vs реальные группы):")
display(coverage_matrix)

Матрица покрытия (хинты vs реальные группы):

              is_painting_hint  is_icon_hint  is_coin_hint  is_doc_hint
target_group
ART                       1700           441            70          296
DOCUMENTS                   28            46            45          338
ICON                        62          2656           336           55
NUMISMATICS                 18             9          1050          127

#### Приведение к одинаковым единицам измерения

In [86]:
import numpy as np
import re

# Словари от ИИ-агента
TO_CM = {
    'см': 1.0, 'см.': 1.0, 'cm': 1.0, 'cм': 1.0, 'cм.': 1.0,
    'мм': 0.1, 'мм.': 0.1, 'mm': 0.1,
    'м': 100.0, 'м.': 100.0, 'm': 100.0,
    'дм': 10.0, 'дм.': 10.0, 'dm': 10.0,
    'дюйм': 2.54,  # английский; если французский — 2.707
    'вершок': 4.445, 'верш': 4.445,
    'аршин': 71.12, 'арш': 71.12,
    'фут': 30.48, 'ft': 30.48,
}
TO_GRAM = {
    'г': 1.0, 'г.': 1.0, 'гр': 1.0, 'гр.': 1.0, 'g': 1.0, 'gr': 1.0,
    'кг': 1000.0, 'кг.': 1000.0, 'kg': 1000.0,
    'мг': 0.001, 'мг.': 0.001, 'mg': 0.001,  # миллиграммы!
}

In [73]:
def smart_convert(value, is_weight=False):
    """
    
    """
    # Превращаем в строку и очищаем от пробелов
    s = str(value).lower().strip()

    # Если ячейка пустая (была NaN или стала ""), возвращаем честный NaN
    if s in ['nan', 'none', '']:
        return np.nan
    
    # Извлекаем первое число из строки
    match = re.search(r"(\d+\.?\d*)", s)
    if not match:
        return np.nan
    
    try:
        num = float(match.group(1).replace(',', '.'))

        # Ищем единицу измерения
        multiplier = None
        if is_weight:
            lookup = TO_GRAM
        else:
            lookup = TO_CM
        
        # Ищем любую единицу из словаря в строке
        for unit, val in lookup.items():
            if unit in s:
                multiplier = val
                break
        
        # Если единиц нет (просто число) — берем значение по умолчанию
        if multiplier is None:
            return num # По умолчанию см или г
        
        return num * multiplier
    
    except:
        return np.nan

In [74]:
def extract_weight_from_text(row):
    """
    
    """
    if pd.notna(row['weight']): 
        return row['weight']
    
    text = f"{row['title']} {row['marks']}".lower()
    # Ищем паттерн: "вес 720 гр" или "вес: 8,5 кг"
    match = re.search(r"вес\s*:?\s*(\d+[.,]?\d*)\s*(гр|г|кг|kg|g)", text)
    if match:
        val = float(match.group(1).replace(',', '.'))
        unit = match.group(2)
        return val * TO_GRAM.get(unit, 1.0)
    
    return np.nan

In [98]:
# Сначала чистим то, что уже в колонках
for col in ['height', 'width', 'length']:
    df_raw[col] = df_raw[col].apply(smart_convert, is_weight=False)

df_raw['weight'] = df_raw['weight'].apply(smart_convert, is_weight=True)

# 2. Дозаполняем ВЕС из текстовых описаний
df_raw['weight'] = df_raw.apply(extract_weight_from_text, axis=1)

# Проверка результата
print("Умная конвертация завершена!")
print("Статистика очистки:")
for col in ['height', 'width', 'length', 'weight']:
    success_count = df_raw[col].notna().sum()
    print(f"Колонка {col}: успешно преобразовано {success_count} числовых значений")

Умная конвертация завершена!
Статистика очистки:
Колонка height: успешно преобразовано 4781 числовых значений
Колонка width: успешно преобразовано 5166 числовых значений
Колонка length: успешно преобразовано 193 числовых значений
Колонка weight: успешно преобразовано 86 числовых значений

In [76]:
df_raw.head()

,title,marks,condition,category,height,width,length,weight,create_date,target_group,is_painting_hint,is_icon_hint,is_coin_hint,is_doc_hint
0,"Каменев И.Ю. ""Фазы луны"" (триптих, центральная...",NaN,NaN,ЖИВОПИСЬ,180.0,120.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
1,"Каменев И.Ю. ""Фазы луны"" (триптих, левая часть...",NaN,NaN,ЖИВОПИСЬ,180.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
2,"Каменев И.Ю. ""Фазы луны"" (триптих, правая част...",NaN,NaN,ЖИВОПИСЬ,180.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,0,0,0
3,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,NaN,ЖИВОПИСЬ,150.0,100.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,1,0,0
4,"Каменев И.Ю. ""Спаситель, попирающий космически...",NaN,NaN,ЖИВОПИСЬ,80.0,60.0,NaN,NaN,2025-12-24T15:53:29+03:00,ART,1,1,0,0

In [99]:
# Загружаем исходный сырой файл для сравнения
df_old = pd.read_csv(DATASET_PATH)
cols = ['height', 'width', 'length', 'weight']

# Считаем количество НЕ пустых значений
before = df_old[cols].notna().sum()
after = df_raw[cols].notna().sum()
recovered = after - before

# Выводим красивую таблицу сравнения
comparison = pd.DataFrame({
    'Было (Raw)': before,
    'Стало (Cleaned)': after,
    'Восстановлено': recovered,
    'Прирост %': (recovered / before * 100).fillna(0).map('{:.1f}%'.format)
})

print("СТАТИСТИКА ВОССТАНОВЛЕНИЯ ДАННЫХ:")
display(comparison)
print(f"\nВсего удалось восстановить {recovered.sum()} числовых значений из текстовых описаний!")

СТАТИСТИКА ВОССТАНОВЛЕНИЯ ДАННЫХ:

        Было (Raw)  Стало (Cleaned)  Восстановлено Прирост %
height        4781             4781              0      0.0%
width         5166             5166              0      0.0%
length         193              193              0      0.0%
weight           0               86             86      inf%

Всего удалось восстановить 86 числовых значений из текстовых описаний!

In [100]:
# Считаем общее количество строк
total_rows = len(df_raw)

# Считаем процент пропусков для КАЖДОЙ колонки отдельно
null_percentages = (df_raw[['height', 'width', 'length', 'weight']].isnull().sum() / total_rows) * 100

print("Процент пропусков по каждой колонке:")
print(null_percentages.map('{:.2f}%'.format))

# Средний процент "пустоты" именно по этим 4-м колонкам
total_nulls_in_subset = df_raw[['height', 'width', 'length', 'weight']].isnull().sum().sum()
total_cells_in_subset = total_rows * 4
actual_empty_percent = (total_nulls_in_subset / total_cells_in_subset) * 100

print(f"Средняя 'пустота' ключевых признаков: {actual_empty_percent:.2f}%")

Процент пропусков по каждой колонке:
height    36.68%
width     31.58%
length    97.44%
weight    98.86%
dtype: str
Средняя 'пустота' ключевых признаков: 66.14%

#### Заполнение пустых ячеек

In [ ]:
RE_3D = re.compile(r'(\d+[.,]?\d*)\s*[xх*×]\s*(\d+[.,]?\d*)\s*[xх*×]\s*(\d+[.,]?\d*)', re.IGNORECASE)
RE_WEIGHT = re.compile(r'вес\s*:?\s*(\d+[.,]?\d*)\s*(гр|г|кг|kg|g|мг)', re.IGNORECASE)

# Словари конвертации
TO_G = {'г': 1.0, 'гр': 1.0, 'кг': 1000.0, 'мг': 0.001}

In [ ]:
def extract_missing_info(row):
    """Пытается вытащить Длину и Вес из текста, если их нет в колонках."""
    text = (str(row['title']) + " " + str(row['marks'])).lower()

    # Извлекаем Длину (если пустая) из паттерна 10х20х30
    if pd.isna(row['length']):
        match_3d = RE_3D.search(text)
        if match_3d:
            row['length'] = float(match_3d.group(3).replace(',', '.'))
            # Если высота или ширина были пустыми — дозаполняем их из этого же паттерна
            if pd.isna(row['height']): row['height'] = float(match_3d.group(1).replace(',', '.'))
            if pd.isna(row['width']): row['width'] = float(match_3d.group(2).replace(',', '.'))

    # Извлекаем Вес (если пустой)
    if pd.isna(row['weight']):
        match_w = RE_WEIGHT.search(text)
        if match_w:
            val = float(match_w.group(1).replace(',', '.'))
            unit = match_w.group(2)
            row['weight'] = val * TO_G.get(unit, 1.0)
            
    return row

In [ ]:
# --- ШАГ 1: Восстановление данных из текста ---
df_raw = df_raw.apply(extract_missing_info, axis=1)

# --- ШАГ 2: Заполнение медианой (STANDALONE STEP) ---
# Заполняем высоту и ширину медианой ПО ГРУППАМ
df_raw['height'] = df_raw['height'].fillna(df_raw.groupby('target_group')['height'].transform('median'))
df_raw['width'] = df_raw['width'].fillna(df_raw.groupby('target_group')['width'].transform('median'))

# --- ШАГ 3: Финальная обработка Длины и Веса ---
# Длину и вес медианой заполнять опасно (слишком много пустоты), 
# поэтому заменяем оставшиеся NaN на 0, чтобы ML-модель могла работать.
df_raw['length'] = df_raw['length'].fillna(0)
df_raw['weight'] = df_raw['weight'].fillna(0)

# Проверка результатов
print("Пропусков после обработки:")
print(df_raw[['height', 'width', 'length', 'weight']].isna().sum())

In [ ]:
import re
# оригинал самый первый
def fill_missing_dimensions(df):
    """

    """
    initial_missing = df[['height', 'width']].isna().sum().sum()

    # Регулярные выражения
    # 1. Размер "Число x Число" (латинская 'x', кириллическая 'х', '*')
    dim_pattern = re.compile(r'(\d+(?:[.,]\d+)?)\s*[xх*]\s*(\d+(?:[.,]\d+)?)', re.IGNORECASE)
    # 2. "диаметр Число"
    diam_pattern = re.compile(r'(?:диаметр|диам\.)\s*(\d+(?:[.,]\d+)?)', re.IGNORECASE)

    def extract_dims(row):
        # Если оба уже есть, ничего не делаем
        if pd.notna(row['height']) and pd.notna(row['width']):
            return row['height'], row['width']

        text = str(row['title']) + " " + str(row['marks'])

        # Поиск 2D размеров
        match_dim = dim_pattern.search(text)
        if match_dim:
            h = float(match_dim.group(1).replace(',', '.'))
            w = float(match_dim.group(2).replace(',', '.'))
            return h, w

        # Поиск диаметра
        match_diam = diam_pattern.search(text)
        if match_diam:
            val = float(match_diam.group(1).replace(',', '.'))
            return val, val

        return row['height'], row['width']

    # Применяем функцию
    new_dims = df.apply(extract_dims, axis=1, result_type='expand')
    df['height'] = new_dims[0]
    df['width'] = new_dims[1]

    final_missing = df[['height', 'width']].isna().sum().sum()
    print(f"Заполнено пропущенных значений: {initial_missing - final_missing}")
    return df

# Применяем к датафрейму
df_raw = fill_missing_dimensions(df_raw)

Заполнено пропущенных значений: 1432

## Easy версия

### Анализ

In [ ]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATASET_PATH = BASE_DIR / "data" / "culture_large_dataset_raw.csv"

if DATASET_PATH.exists():
    df_raw = pd.read_csv(DATASET_PATH)
    print("Датасет успешно загружен.")
    print(f"Строк: {len(df_raw)}")
else:
    print(f"Файл не найден по пути: {DATASET_PATH}")